name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  unit:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v1

      - name: Lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy
